default:
  twitter:
    BASE_URL: "http://localhost:8080/api/v1/"
    HEADERS:
      accept: 'application/json'
      Content-Type: 'application/json'
    TWEETS_PER_REQUEST: 150  # Number of tweets to fetch per request
    START_DATE: '2024-08-15'  # Start date for fetching tweets
    END_DATE: '2024-08-17'  # End date for fetching tweets
    DAYS_PER_ITERATION: 1 
    MAX_RETRIES: 3
    BASE_WAIT_TIME: 10
    BACKOFF_FACTOR: 2
    MAX_WAIT_TIME: 960
    SUCCESS_WAIT_TIME: 10
    RETRYABLE_EXCEPTIONS:
      - NetworkException
      - RateLimitException
      - APIException
      - NoWorkersAvailableException
      - GatewayTimeoutException
    INITIAL_WAIT_TIMES:
      '429': 120
      '417': 960  
      '504': 60   
    DEFAULT_TIMEFRAME_MONTHS: 1 

  request_manager:
    STATE_FILE: "src/masa_ai/orchestration/request_manager_state.json"
    QUEUE_FILE: "src/masa_ai/orchestration/request_queue.json"

  data_storage:
    DATA_DIRECTORY: null

  logging:
    LOG_LEVEL: DEBUG
    LOG_FORMAT: "%(asctime)s - %(levelname)s - %(message)s"
    LOG_DATE_FORMAT: "%Y-%m-%d %H:%M:%S"
    CONSOLE_LOG_LEVEL: INFO
    FILE_LOG_LEVEL: DEBUG
    COLOR_ENABLED: true
