name: masa
channels:
  - defaults
  - conda-forge
dependencies:
  - colorlog
  - dynaconf
  - feedparser
  - ipykernel
  - jupyter
  - matplotlib
  - notebook
  - numpy
  - openai
  - pandas
  - pip
  - python-dotenv
  - python=3.12
  - pyyaml
  - recommonmark
  - requests
  - scikit-learn
  - sphinx
  - sphinx_rtd_theme
  - myst-parser
  - streamlit
  - tiktoken
  - tqdm
  - pip:
    - -r requirements.txt