name: masa
channels:
  - defaults
  - conda-forge
dependencies:
  # Core dependencies
  - python=3.12
  - pip
  - numpy
  - pandas
  - pyyaml
  - python-dotenv
  - requests
  - tqdm

  # Logging and configuration
  - colorlog
  - dynaconf

  # Data processing and visualization
  - matplotlib
  - scikit-learn

  # Jupyter and IPython
  - ipykernel
  - jupyter
  - notebook

  # Documentation
  - sphinx
  - sphinx_rtd_theme
  - recommonmark
  - myst-parser

  # Web and API
  - streamlit

  # Natural Language Processing
  - tiktoken
  - openai

  # Miscellaneous
  - feedparser

  # Install additional dependencies from requirements.txt
  - pip:
    - -r requirements.txt