name: masa
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pyyaml
  - jupyter
  - notebook
  - ipykernel
  - matplotlib
  - numpy
  - pandas
  - scikit-learn
  - streamlit
  - requests
  - python-dotenv
  - feedparser
  - openai
  - tiktoken
  - tqdm
  - colorlog
  - pip
  - sphinx
  - sphinx_rtd_theme
  - recommonmark
  - pip:
    - -r requirements.txt