default:
  twitter:
    # BASE_URL: "https://api.twitter.com/2/"
    BASE_URL_LOCAL: "http://localhost:8080/api/v1/"
    HEADERS:
      accept: 'application/json'
      Content-Type: 'application/json'
    TWEETS_PER_REQUEST: 150  #: Number of tweets to fetch per request
    START_DATE: '2024-08-27'  #: Start date for fetching tweets
    END_DATE: '2024-08-29'  #: End date for fetching tweets
    DAYS_PER_ITERATION: 1  #: Number of days to fetch tweets for in each iteration
    MAX_RETRIES: 3
    BASE_WAIT_TIME: 10
    BACKOFF_FACTOR: 2
    MAX_WAIT_TIME: 960
    RETRYABLE_EXCEPTIONS:
      - NetworkException
      - RateLimitException
      - APIException

  request_manager:
    STATE_FILE: "orchestration/request_manager_state.json"  #: File path for storing the state of the request manager.
    QUEUE_FILE: "orchestration/request_queue.json"  #: File path for storing the request queue.

  logging:
    LOG_LEVEL: INFO
    LOG_FILE: "logs/masa.log"
    LOG_FORMAT: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    LOG_DATE_FORMAT: "%Y-%m-%d %H:%M:%S"

development:
  logging:
    LOG_LEVEL: DEBUG
