# Add start_time and end_time
start_time: '2024-08-01T00:00:00Z'
end_time: '2024-08-14T00:00:00Z'

# Headers
headers:
  accept: 'application/json'
  Content-Type: 'application/json'

# Interval to wait after successful retrieval (in seconds)
TWITTER_SUCCESS_INTERVAL: 7

# Delay for retry after rate limiting (in seconds)
TWITTER_RETRY_DELAY: 960